'use client'

import { useState } from 'react'
import { ResearchForm } from '@/components/research/research-form'
import { AgentStatusPanel } from '@/components/research/agent-status-panel'
import { ResultsDisplay } from '@/components/research/results-display'
import type { ResearchRequest, AgentStatus, ComparisonResult } from '@/lib/types'

export default function ResearchPage() {
  const [isLoading, setIsLoading] = useState(false)
  const [agents, setAgents] = useState<AgentStatus[]>([
    { model_name: 'gpt-4o', status: 'idle' },
    { model_name: 'gemini-2.5-flash', status: 'idle' },
    { model_name: 'deepseek-r1:14b', status: 'idle' },
  ])
  const [result, setResult] = useState<ComparisonResult | null>(null)

  const handleSubmit = async (data: ResearchRequest) => {
    setIsLoading(true)
    setResult(null)

    // Update all agents to running status
    setAgents((prev) =>
      prev.map((agent) => ({ ...agent, status: 'running' as const }))
    )

    // TODO: Replace with actual API call in Phase 4
    // Simulate API call for now
    setTimeout(() => {
      // Simulate completion
      setAgents((prev) =>
        prev.map((agent) => ({ ...agent, status: 'completed' as const }))
      )

      // Mock result
      const mockResult: ComparisonResult = {
        query: data.query,
        domain: data.domain,
        responses: {
          'gpt-4o': {
            query: data.query,
            domain: data.domain,
            answer: 'This is a mock response from GPT-4o. In Phase 4, this will be replaced with actual API responses.',
            confidence: 0.92,
            sources: [],
            model_name: 'gpt-4o',
            tokens_used: 150,
            timestamp: new Date().toISOString(),
          },
          'gemini-2.5-flash': {
            query: data.query,
            domain: data.domain,
            answer: 'This is a mock response from Gemini 2.5 Flash. In Phase 4, this will be replaced with actual API responses.',
            confidence: 0.88,
            sources: [],
            model_name: 'gemini-2.5-flash',
            tokens_used: 140,
            timestamp: new Date().toISOString(),
          },
          'deepseek-r1:14b': {
            query: data.query,
            domain: data.domain,
            answer: 'This is a mock response from DeepSeek R1. In Phase 4, this will be replaced with actual API responses.',
            confidence: 0.85,
            sources: [],
            model_name: 'deepseek-r1:14b',
            tokens_used: 160,
            timestamp: new Date().toISOString(),
          },
        },
        total_agents: 3,
        successful_agents: 3,
        failed_agents: [],
        consensus_points: ['All models agree on the main concept', 'Similar confidence levels'],
        disagreement_points: [],
        confidence_range: '85-92%',
        synthesized_answer:
          'This is a synthesized answer combining insights from all three models. In Phase 4, this will be generated by the ResponseAggregator based on actual agent responses.',
        timestamp: new Date().toISOString(),
        total_tokens: 450,
        total_cost: 0.0015,
      }

      setResult(mockResult)
      setIsLoading(false)

      // Save to recent searches
      const recentSearches = JSON.parse(
        localStorage.getItem('recent_searches') || '[]'
      )
      recentSearches.unshift({
        id: Date.now().toString(),
        query: data.query,
        timestamp: new Date().toISOString(),
      })
      localStorage.setItem(
        'recent_searches',
        JSON.stringify(recentSearches.slice(0, 10))
      )
    }, 3000)
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Research</h1>
        <p className="text-muted-foreground">
          Start a new research session with the LLM Council
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        <div className="lg:col-span-2 space-y-6">
          <ResearchForm onSubmit={handleSubmit} isLoading={isLoading} />
          {result && <ResultsDisplay result={result} />}
        </div>

        <div>
          <AgentStatusPanel agents={agents} />
        </div>
      </div>
    </div>
  )
}
